#!/usr/bin/env Rscript

# This script takes the beast output tree (summarized maximum clade credibility tree generated by TreeAnnotator), chooses the location with the highest posterior for each node and writes the tree in Newick format and the corresponding locations as a text file (to ensure that the output can be read by the Fréchet tree distance script for evaluation).
# Input are the tree and the prefix for the output files.

library("ggtree")

args = commandArgs(trailingOnly=TRUE)
input = args[1]
output = args[2]

# read beast output using function from ggtree package
beast <- read.beast(input)
# get phylogenetic tree
beast_tree <- beast@phylo

# get possible locations and probabilities
loc_sets <- beast@stats$location.set
prob_sets <- beast@stats$location.set.prob

locations <- vector(mode = "character", length = length(loc_sets))

# go over all internal nodes and choose location with the highest posterior probability
for (i in 1:length(loc_sets)){
  index <- which(prob_sets[[i]] == max(prob_sets[[i]]))
  index <- index[1] # in case of ambiguities: take first option
  locations[i] <- loc_sets[[i]][index]
}

# order locations by node id
locations_ordered <- locations[order(as.integer(beast@stats$node))]

# add internal node ids
n_nodes <- beast_tree$Nnode
node_label <- paste("intNode", seq(1, n_nodes), sep="")
beast_tree$node.label <- node_label

# create annotation
node_annotation <- data.frame(label=c(beast_tree$tip.label, beast_tree$node.label), location=locations_ordered)

# save data
write.tree(beast_tree, paste(output,".phy", sep=""))
write.table(node_annotation, paste(output, ".annotation.txt", sep=""), quote=FALSE, row.names=FALSE, sep="\t")
